steps : 
 - name : 'gcr.io/cloudibuilders/gcloud'
   id : Update staging server
   entrypoint: /bin/sh
   args:
   - '-c'
   - |
      set -x && \
      gcloud compute ssh nginx --zone=us-central1-a --command='/bin/sh ./script.sh'